# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environmentConfiguration:
        description: 'Environment to run tests against(ex: qa, dev)'
        type: environment
        required: false
        default: 'qa'
      browser:
        description: 'The browser to run on(ex: ChromeDriver, FireFoxDriver'
        type: environment
        required: false
        default: 'ChromeDriver'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Test with Gradle
        run: ./gradlew cucumber
