# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: choice
        required: true
        default: 'qa'
        options:
          - 'qa'
          - 'dev'
      browserSetup:
        description: 'The browser to run on'
        type: choice
        required: true
        default: 'ChromeDriver'
        options:
          - 'ChromeDriver'
          - 'FireFoxDriver'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Environment and Browser configuration
        run: echo "The ENVIRONMENT is ${{ github.event.inputs.environment }} && browser is ${{ github.event.inputs.browserSetup }}"
      - name: Saving environment variables
        run: echo "environmentConfiguration}={${{ github.event.inputs.environment }}}" >> $GITHUB_ENV 
             echo "{browser}={${{ github.event.inputs.browserSetup }}}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Test with Gradle
        run: ./gradlew cucumber