# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environmentConfiguration:
        description: 'Environment to run tests against'
        type: choice
        required: false
        default: 'qa'
        options:
          - qa
          - dev
env:
  environmentConfiguration: github.event.inputs.environmentConfiguration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Test with Gradle
        run: ./gradlew cucumber
